### ISSUE TITLE
Cannot interact

### ISSUE THREAD

**Issue by OudomMunint** [naweed/Maui.Controls.BottomSheet#7]
Bottom sheet shows but can't be interacted with nor be closed

**Comment by naweed** [comment]
It was working earlier. May be something brown in latest Maui version. Maui is highly unstable platform. I have stopped working on it altogether, so cannot help you.

**Comment by OudomMunint** [comment]
I found the issue, in the BottomSheet.xaml, InputTransparent is set to True, when I changed it to false, I can interact with it again. Someone must've accidentally changed it
